[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm run build"
startCommand = "npm start"

[services.healthcheck]
path = "/health"
timeout = 300

[services.variables]
NODE_ENV = "production"
PORT = "4000"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production" 