[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[mounts]]
source = "uploads"
destination = "/app/uploads" 